---
- hosts: "grafana"
  become: true
  gather_facts: no
  vars:
    - to_bin: grafana/bin/
    - to_etc: grafana/prometheus/
    - to_sys: grafana/prometheus.service
    - to_rep: grafana/grafana.repo
  tasks:    

# prometheus
  - name: Create user prometheus
    user:
      name: prometheus
      create_home: no
      shell: /usr/sbin/nologin

  - name: Copy to /etc/
    copy:
      src: '{{ to_etc }}'
      dest: /etc/prometheus/
      owner: prometheus
      group: prometheus
      mode: 'preserve'

  - name: Copy to /usr/local/bin/
    copy:
      src: '{{ to_bin }}'
      dest: /usr/local/bin/
      owner: prometheus
      group: prometheus
      mode: 'preserve'

  - name: Copy to systemd
    copy:
      src: '{{ to_sys }}'
      dest: /etc/systemd/system/
      owner: root
      mode: 'preserve'

  - name: Create /var/lib/prometheus
    file:
      path: /var/lib/prometheus
      mode: '0755'
      owner: prometheus
      group: prometheus
      state: directory

  - name: Start service prometheus
    systemd:
      daemon_reload: yes
      name: prometheus
      enabled: yes
      state: started

# grafana
  - name: Copy file
    copy:
      src: grafana/grafana-enterprise-9.4.3-1.x86_64.rpm
      dest: /tmp

  - name: Install Grafana
    yum:
      name: /tmp/grafana-enterprise-9.4.3-1.x86_64.rpm
      state: present

  - name: Start service Grafana
    systemd:
      daemon_reload: yes
      name: grafana-server
      enabled: yes
      state: started

